### ISSUE TITLE
Need more description for Keycloak Setup

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-aaa-server#224] opened 2022-08-25 06:35 UTC
Hi Team,

I am trying to setup IUDX Auth server on my local by following readme doc from tag v3.5.0.

After installing keycloak while following step1 from section **Keycloak Setup** to configure normal client, Then i am unable to understand what actually i need perform there.

Can i have more descriptive doc to setup keycloak.

Thanks

**Comment by ThorodanBrom** [comment] 2022-08-26 09:12
Hello @pachori91

Thanks for raising the issue. We will be adding a detailed guide for the Keycloak setup to our v3.5.0 branch. For now, I will list out the main steps that need to be followed.

### Prerequisite

Ensure that you have installed Keycloak **version 14.0.1**. (Newer versions of Keycloak are incompatible with the v3.5.0.branch).

Read the [Keycloak core concepts and terminology](https://www.keycloak.org/docs/14.0/server_admin/#core-concepts-and-terms) page to understand the different terms like realms, clients, roles etc. We will be referring to these terms here onwards.

### Admin and realm creation

Once installed, you will need to create an admin user and create a new realm. **We advise you to not reuse the `master` realm here.** The Keycloak [getting started guide](https://www.keycloak.org/docs/14.0/getting_started/) details how to do both of these steps. 

(You may also see the [Server Initialization](https://www.keycloak.org/docs/14.0/server_admin/#server-initialization) and [Create Realm](https://www.keycloak.org/docs/14.0/server_admin/#_create-realm) for admin creation and realm creation respectively)

### Login settings 

In the admin console page, with the realm set to the one you just created, you will need to add the login settings. See [here](https://www.keycloak.org/docs/14.0/server_admin/#login-page-settings) for the different settings that can be enabled. The settings that need to be as follows
    - `User registration` : **ON**
    - `Email as username` : **ON**
    - `Edit username` : **OFF**
    - `Forgot password` : **ON** _(see [SMTP Configuration](#SMTP-Configuration))_
    - `Verify email` : **ON** _(see [SMTP Configuration](#SMTP-Configuration))_
    - `Login with email` : **ON**

#### SMTP Configuration
For `Forgot password` and `Verify email` to work, an SMTP connection needs to be configured. This is to allow Keycloak to send emails to the user containing a reset password link or a verification link respectively. 

See [Email Settings](https://www.keycloak.org/docs/14.0/server_admin/#_email) to configure SMTP for the realm you created. 

### Adding roles

You will now need to add roles to the realm. Refer to [Realm Roles](https://www.keycloak.org/docs/14.0/server_admin/#realm-roles) on how to do this.

The roles that are to be added are:
    - `consumer`
    - `delegate`
    - `provider`
    - `admin`
    - `trustee`

### Adding clients

Next, you will need to add clients to the realm. These clients are used by the AAA server to connect to Keycloak and perform certain tasks. Refer to [OIDC Clients](https://www.keycloak.org/docs/14.0/server_admin/#oidc-clients) to see how to add new clients and the different options present in the client settings.

#### Admin client

Create a new client with the Client ID as `keycloak-admin`. Once created, update the client settings in the `Settings` tab:

- `Access Type` set to **confidential**
- `Standard Flow Enabled` set to **OFF**
- `Direct Access Grants Enabled` set to **OFF**
- `Service Accounts Enabled` set to **ON** _(this only appears if Access Type is confidential)_

Save the settings after this. Once saved, a new tab called `Credentials` will appear, containing the client secret. This, along with the client ID are required when configuring the AAA server. See [Client Credentials](https://www.keycloak.org/docs/14.0/server_admin/#_client-credentials) for more information.

Another tab called `Service Account Roles` also appears. See [Service Accounts](https://www.keycloak.org/docs/14.0/server_admin/#_service_accounts) for more information. In this tab, you can configure the roles the client can have. In the `Service Account Roles` tab:

- In the `Client Roles` bar, go to `realm-management` and select it (see [Dedicated Realm Admin Consoles](https://www.keycloak.org/docs/14.0/server_admin/#_per_realm_admin_permissions) for more information)
- In the `Available Roles` select box, add the following roles to the `Assigned Roles` box:
    - `manage-users`
    - `view-realm`
    - `view-users`

The configuration for the `keycloak-admin` client is complete

#### Normal client

Create a new client with the Client ID as `auth.iudx.org.in`. Once created, update the client settings in the `Settings` tab:

- `Access Type` set to **confidential**
- `Standard Flow Enabled` set to **OFF**
- `Direct Access Grants Enabled` set to **OFF**
- `Service Accounts Enabled` set to **ON** _(this only appears if Access Type is confidential)_

Save the settings after this. Once saved, a new tab called `Credentials` will appear, containing the client secret. This, along with the client ID are required when configuring the AAA server. See [Client Credentials](https://www.keycloak.org/docs/14.0/server_admin/#_client-credentials) for more information.

### Post configuration

Once Keycloak is configured, the Keycloak host, port, client IDs and client secrets need to be added to the config of the AAA server. Please refer to this [example config](https://github.com/datakaveri/iudx-aaa-server/blob/3.5.0/configs/config-example.json) for more information. In the example config,

- `keycloakAdminClient...` corresponds to the [Admin client](#Admin-client)
- `keycloakAaaClient...` corresponds to the [Normal client](#Normal-client)

**Comment by pachori91** [comment] 2022-08-26 11:39
Thanks you very much @ThorodanBrom for you reply.  
It's really helpfull for me.

**Comment by pachori91** [comment] 2022-08-31 10:36
Hi Team,

I have followed steps as mentioned by @ThorodanBrom and able to start Auth, Catalouge and Resource server on my local.

Furhter i am trying to create an organization by using Auth server API /auth/v1/admin/organizations. But now i am unable to find from where i will get admin access token to call this api. so that auth server will create organization for me.

May be i am stupid here but please help me guys here.

Thanks
Deepak Kumar

**Comment by pachori91** [comment] 2022-09-01 04:41
@ThorodanBrom i hope you might be busy. But could you please find some time to reply on above query.
it's delaying my timeline.
It would be highly appreciable.

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment] 2022-09-01 04:57
Hello @pachori91 ,

We will need to prepare a small guide to setup the admin users on the auth server. Please give us some time to do so. But first, the Keycloak-AAA interactions need to be working, that should be the priority now.

**Comment by pachori91** [comment] 2022-09-01 06:22
Thanks for your reply @ThorodanBrom .
My keycloak-AA interaction is working fine. 
 
Further i followed below steps-
**step1**-  Created a new user under my realm and assigned role as realm mangement to it. below is screen for same-
![image](https://user-images.githubusercontent.com/105433601/187843740-08442dc5-2d18-4f59-9e06-d7b2c8248f9b.png)
**step2** -  Obtain access token for a user by using keycloak api as per below-
![image](https://user-images.githubusercontent.com/105433601/187844682-7c0c831a-ac73-4ee9-b591-0d2a08f0c1ca.png)

**Step3 -** Now finally i am trying to create organization by using Auth Server's API as per below screen by passing accesstoken got in Step2-

![image](https://user-images.githubusercontent.com/105433601/187845331-f80a9657-35fd-4ce8-9e92-eab61418d5e7.png)

but i am getting below json as response -
{
    "type": "urn:dx:as:MissingInformation",
    "title": "User profile does not exist",
    "detail": "Please register to create user profile"
}

My be i am doing anything wrong here.
Can you please help me here it will be really helpfull for me

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment] 2022-09-01 07:28
Hello @pachori91

Glad to know that Keycloak is working fine. The auth admin setup does not involve Keycloak as you have tried to do, below are the steps for it:

**NOTE**: The auth admin setup is part of the bootstrap for the auth server, and requires you to run queries on the auth database.

### Creating the first user on Keycloak and on the auth server
- First, create a user on Keycloak with a password. You can either do this on the Admin Console or on the keycloak account page - `http/https://{Keycloak hostname}/auth/realms/{realmname}/account/`
- Once the user is created on Keycloak, create a user profile on the auth server using the [Create User Profile](https://authorization.iudx.org.in/apis#tag/User-APIs/operation/post-auth-v1-user-profile) API. You may use the [auth Postman collection](https://github.com/datakaveri/iudx-aaa-server/tree/3.5.0/src/main/resources/postman) for this - get a token, (the instructions to get the token are in the README of the Postman collection) and call the create user profile API with this request body
```json
{
    "roles": ["consumer"]
}
```
- If this was a success, we now have created a user with consumer role on the auth server.

### Updating the role of the user
- The current auth server implementation does not allow users to acquire the `admin` role. It can only be added as a backend operation (this is mainly because creation of admins is infrequent)
- The auth PostgreSQL DB should have a **single user** in the `users` table and a single row in the `roles` table
- Since this user intends to be an auth admin, we update the role of this user in the `roles` table to be `admin` with the below query.
```sql
UPDATE <schema>.roles SET role = 'ADMIN';
```
### Adding an entry to `resource_server` table
- We now make an entry into the `resource_servers` table to add the auth server URL to the system. The URL configured here must be the same URL configured in the `config-*.json` `commonOptions` -> `authServerDomain`. 
In the SQL query below, `owner_id` is the user ID`(id` in the `users` table) of the user we just created and updated. 
```sql
INSERT INTO <schema>.resource_server (name, owner_id, url, created_at, updated_at) VALUES ('Test Auth Server', '<user ID>'::uuid, '<auth server url e.g. testauthserver.com>', NOW(), NOW());
```
**NOTE**: The RS and Cat servers may also have admins associated with them. You can use the same user as admins for the other servers. If this is what you desire, the only changes in the query would be the `url` and `name`
e.g.
```sql
INSERT INTO <schema>.resource_server (name, owner_id, url, created_at, updated_at) VALUES ('Test Resource Server', '<user ID>'::uuid, '<RS url e.g. testrs.com>', NOW(), NOW());
```
### Conclusion

You have now created the auth admin user. As long as the config is configured with the correct auth URL (i.e. whatever has been entered into the `resource_server` table). Using this user's credentials, you should be able to [create organizations](https://authorization.iudx.org.in/apis#tag/Organization-APIs) and [approve providers](https://authorization.iudx.org.in/apis#tag/Admin-APIs/operation/put-auth-v1-admin-provider-registrations)

--------------
We understand this may be a little complicated to execute, since these are slightly non-standard flows. Let us know if you face any difficulty or have any issues.

**Comment by pachori91** [comment] 2022-09-02 07:45
Thanks @ThorodanBrom for your reply, it's really helfull and i followed same steps.

So finally i have created Admin, Provider and Delegate User and Organization and able to see same in Postgres Db Also.

Now Goal is to register adaptor so that i can stream my data to databroker. On the way to achieve same i am trying to register Metadata About My Resources on catalogue server, for that i am following doc [Manage Metadata](https://docs.iudx.org.in/docs/provider/provider_register_catalogue_item/).

As per this doc i am trying to call [Create Token API](https://authorization.iudx.org.in/apis#tag/Token-APIs/operation/post-auth-v1-token) to get token to register my Resource to catalogue server by sending payload as below-
{
    "itemId": "gmail.com/<sha1- of provider email>/localhost/catalogue/crud",
    "itemType": "resource",
    "role": "provider"
}
this api is responding with Internal Server error, Further i debugged implementation and found it is trying to call Catalogue Api
Get  - http://mycatatalogue-host:port/iudx/cat/v1/item?id=gmail.com/4963c4b2286fd33f9544d790f03757352f88a82b/localhost/catalogue/crud.

SO further i debugged http://mycatatalogue-host:port/iudx/cat/v1/item api and found it is looking in connected Elastic with query - 
{"_source":[],"query":{"term":{"id.keyword":"gmail.com/4963c4b2286fd33f9544d790f03757352f88a82b/localhost/catalogue/crud"}}}.

which is not present in my elastic and i have setup my elastic by following doc - https://github.com/datakaveri/iudx-deployment/tree/master/Docker-Swarm-deployment/single-node/elk.

SO my question is what are the further steps i need to follow so that catalogue and resource server will be configured in such a way so that i can register my adaptor to my Resource server to stream my data .

Sorry for long text. But i need help here.

May be i am missing some required setps to setup catalogue server and resource server. 

Sorry again as i am asking again and again, but it blocking my timeline so please reply as soon as possible.


Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment] 2022-09-02 08:37
Hello @pachori91 

Glad to hear that the auth setup was successful. 

Unfortunately, I am not very familiar with the setup for the catalogue and the resource server, so it would be best to make issues with respect to the errors you are facing in the respective repositories, or even in the iudx-deployment repository.

Let me try to help with what I understand from what you have explained:
- I think that you may need to create some items on the catalogue, like the resource server item. You can get in touch with @rraks or @pranavrd on the iudx-catalogue-server repo with regard to this. If you have already done this, please ignore.

- I suggest giving a fake catalogue URL and a fake resource server for this instead of using localhost, it may make things a little easier for you going forward.  (You can possibly use `/etc/hosts` to map these URLs to 127.0.0.1, but be wary of port conflicts). 

- You will need to create entries into the `resource_server` table for the resource server and the catalogue. Again, make sure that the URLs you add here are the ones you intend to use. I mentioned the query for this in my previous answer

> NOTE: The RS and Cat servers may also have admins associated with them. You can use the same user as admins for the other servers. If this is what you desire, the only changes in the query would be the url and name
e.g.
>```sql
>INSERT INTO <schema>.resource_server (name, owner_id, url, created_at, updated_at) VALUES ('Test Resource Server', '<user ID>'::uuid, '<RS url e.g. testrs.com>', NOW(), NOW());
>```

- When creating catalogue items and performing data ingestion with a delegate, there need to be certain policies and certain delegations set by the provider and admin policies set by the server admin. **I suggest that you avoid the delegate flow, and use the provider user you have created for both data ingestion to the resource server and for item creation in the catalogue.** However, **there need to be admin policies for the provider by the catalogue server admin and the resource server admin**. Using the server admin credentials, set a policy for the provider user using the [create policy API](https://authorization.iudx.org.in/apis#tag/Policies-APIs/operation/post-auth-v1-policies). The policies would look like this:

`For resource server using the resource server admin credentials`
```json
{
  "request": [
    {
      "userId": "<UUID user ID of provider>",
      "itemId": "<resource server UR>",
      "itemType": "resource_server",
      "constraints": {}
    }
  ]
}
```
`For catalogue using the catalogue admin credentials`
```json
{
  "request": [
    {
      "userId": "<UUID user ID of provider>",
      "itemId": "<catalogue server UR>",
      "itemType": "resource_server",
      "constraints": {}
    }
  ]
}
``` 

- A proper catalogue token flow does not require a query to the catalogue. I gather from this that the config may be incomplete -  **you will need to update the auth config with the URL of the catalogue you have deployed and port it is running at**. Update it accordingly [here](https://github.com/datakaveri/iudx-aaa-server/blob/6824a4b7f747cdc46e86469960b870068ac8f26d/configs/config-example.json#L45-L47) and [here](https://github.com/datakaveri/iudx-aaa-server/blob/6824a4b7f747cdc46e86469960b870068ac8f26d/configs/config-example.json#L54).
If the catalogue URL was configured, auth would have recognized that you made a catalogue token query via the resource ID `<catalogueUrl>/catalogue/crud`. 

Once the catalogue admin-provider policy is set, and the config with the catalogue URL is updated, you should be able to get a catalogue ingestion token.

**Comment by pachori91** [comment] 2022-09-04 11:13
Hi @ThorodanBrom,

Thanks for your reply, Just need one confirmation -

I have my Auth, Catalogue and Resource Server running on different port but on same system.
So Url for those are like localhost:8081, localhost:8083, localhost:8085.

So when i am trying to provide these address in my create policy request payload then getting invalid syntax error from server.
Like below - 

{
    "type": "urn:dx:as:InvalidInput",
    "title": "Malformed request/missing or malformed request parameters",
    "detail": "[Bad Request] Validation error for body application/json: anyOf subschemas don't match. Multiple causes: [provided string should respect pattern ^[a-zA-Z0-9_*\\-*\\.\/]+$, provided object should contain property userClass]"
}

My request payload is  - 
{
  "request": [
    {
      "userId": "62af8394-acd5-4d59-ab6e-8918f6716d4b",
      "itemId": "localhost:8083",
      "itemType": "resource_server",
      "constraints": {}
    }
  ]
}


Is there anyway so that i can deploy my servers on same system?  Or it is required to have three domain to be assign to these server instances? 
I apologies if asking silly question.

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment] 2022-09-04 13:11
Hello @pachori91 

- If you are not using docker, you can try to use [`/etc/hosts`](https://tldp.org/LDP/solrhe/Securing-Optimizing-Linux-RH-Edition-v1.3/chap9sec95.html) to [set URLs to map to 127.0.0.1](https://www.tecmint.com/setup-local-dns-using-etc-hosts-file-in-linux/). For example, you can configure it like this:

```
127.0.0.1	<rs-url>
127.0.0.1	<cat-url>
127.0.0.1	<auth-url>
```
The problem is that `/etc/hosts` only maps domains, not ports. You will have to use something like nginx as a reverse proxy to forward the request to the correct port depending on the domain.

- If you are using docker, you can try something like [this](https://www.packt.com/container-linking-and-docker-dns/) using `docker network` to override the DNS configuration of the containers. I think if you do this, you can set custom domains/URLs for each container/server and docker will take care of the resolution for you.

**Comment by pachori91** [comment] 2022-09-22 06:29
Hi Team,

One more query regarding expiry time of token on IUDX platform not on my local setup-
Suppose as a provider i obtain a token using Auth Server's create token API.

Then what will be the expiry time for that. 
Is there any default time for which the token will be valid?
Can we change that default expiry time on IUDX platform?

Thanks
Deepak Kumar

**Comment by ThorodanBrom** [comment] 2022-09-26 07:05
Hello @pachori91 

- All JWT tokens issued by the auth server have an expiry time (the `exp` field) 
- By default, the expiry time for the tokens is **12 hours** from time of issue
- The expiry time for a token is currently **not configurable** 
- This is the constant that determines the expiry time in the code - https://github.com/datakaveri/iudx-aaa-server/blob/5a0e0f10f75f6fb7b7ec027ffffb7a8684576291/src/main/java/iudx/aaa/server/token/Constants.java#L15

**Comment by ThorodanBrom** [comment] 2024-03-22 06:24
Closing issue since the working of the auth server has changed significantly since version 5.0.0

**Closed by ThorodanBrom** 2024-03-22 06:24 UTC
